### ISSUE TITLE
Need Natural Earth icon

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief-icons#43]
@sammy1985:

We have icons for the range of screen objects that can be added to my app:
![layers](https://cloud.githubusercontent.com/assets/1108513/5723255/8a067c14-9b3a-11e4-90eb-6b46555d7dc0.png)

As you can see, I need one for the **Natural Earth** plugin.  Natural Earth data comes from this web-site:
http://www.naturalearthdata.com/

The icon needs to use our red/blue color scheme.  We've already got some _Globe_-style icons in there.  But, I'd like you to produce a new icon for this Natural Earth data please, maybe using clues from the website.

As a fallback, maybe you could just us the N and E letters - but that's just a fallback (it would look a bit lazy).

**Comment by sammy1985** [comment]
Hi Ian,

what you think about this one?

Thanks
Sam

**Comment by IanMayo** [comment]
Sam, you haven't attached an image. You just have to drag it in.

**Comment by PixHive** [comment]
![natural-earth](https://cloud.githubusercontent.com/assets/8927540/5833857/91e6dc64-a17d-11e4-9e0d-eb724d4c95e1.png)

**Comment by PixHive** [comment]
Hey Ian Please take a look of this icon for natural earth.

**Comment by IanMayo** [comment]
Nice thinking - I see the "natural" meaning in the branch. But I'm afraid it has to work at 16px (see the examples in the image at the top of the page).

I suspect it's going to have to be a more simple design.

**Comment by PixHive** [comment]
![natural-earth_1_64px](https://cloud.githubusercontent.com/assets/8927540/5834275/aa4203de-a181-11e4-9e70-cddd1a0f01cf.png)
![natural-earth_1](https://cloud.githubusercontent.com/assets/8927540/5834276/aa484a50-a181-11e4-8996-886cb5f01542.png)

**Comment by PixHive** [comment]
Check this...its tree based earth concept. work on 16px tooo...

**Comment by IanMayo** [comment]
@sammy1985  - I've just realised that I wish to use the icon in two places, so I need 16px and 24px versions, please.

24px may give you a little more freedom for an interesting design.
