### ISSUE TITLE
SVG icons need to be centered in their viewport

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief-icons#54]
I'm re-using these icons in another app.  But, the renderer (d3) is struggling to put them in the correct location.

The SVG is centred in the correct place, but some icons aren't centered in the SVG file:
![image](https://user-images.githubusercontent.com/1108513/54365828-7f21ad00-4667-11e9-8ff6-be44b712d35e.png)

Here are the icons with shaded backgrounds, so we can see their bounds:
https://debrief-icons.herokuapp.com/svg/index_borders.html

Actually, it just looks like `floating_mine` and `bottomed_mine` are the only two that need adjusting.

Can you edit these two icons so that the shape is centered within the SVG file?

**Comment by hlaposhka** [comment]
Yes, of course. Initially centering was on the red dot. Leave it in the center of the icon or in the center of the file?

**Comment by IanMayo** [comment]
The red dot will stay in the same place on the icon. But, the bottom of the file will be trimmed, so that the whole shape is in the centre of the file.  Does that make sense?

**Comment by hlaposhka** [comment]
That is, it is not necessary to preserve the proportion of the file? Then I can cut file

**Comment by IanMayo** [comment]
Oh, I forgot that they were already square.

In that case, it would be ok to move the icon down into the centre of the file (with the red dot moving down, too).

**Comment by IanMayo** [comment]
Done.
