### ISSUE TITLE
Missing icons: Cut, Copy, Delete

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief-icons#57]
I've realised we have some missing icons.  So, I don't think we even have a .ai file for them.

So, we'll need a fresh design, please, plus copies placed in 16, 24 and 48 px folders..

![image](https://user-images.githubusercontent.com/1108513/54819965-7fd4c780-4c95-11e9-99d3-5e68c46f152e.png)

**Comment by hlaposhka** [comment]
Copy icon very similar for icon copy_to_clipboard. Can we use it?
<img width="384" alt="2019-03-25 в 14 31 57" src="https://user-images.githubusercontent.com/7010233/54920016-d434ad00-4f0a-11e9-8daa-f44c46e74d23.png">

**Comment by IanMayo** [comment]
Sure, that's fine.

**Comment by hlaposhka** [comment]
Then I will add just cut and delete

**Comment by IanMayo** [comment]
Done.
