### ISSUE TITLE
Thinner border for Exit icon

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief-icons#66]
We have `help` and `exit` icons:
![image](https://user-images.githubusercontent.com/1108513/55541137-48661200-56bc-11e9-9092-acdfa57ddc99.png)

But, the border on the `exit` button is very bold. 

Could you re-create the `exit` buttons with a more narrow border/box?

We'd need ai, 16px, 24px and 48px, please.

**Comment by hlaposhka** [comment]
Could you send me the layout of what all the icons on this panel look like? Perhaps it is worth formatting them all in one thickness.

**Comment by IanMayo** [comment]
Good thinking Yana :-)

I'm sorry but here's the panel:
![image](https://user-images.githubusercontent.com/1108513/55578559-21383080-570e-11e9-80a2-25cb842c11b3.png)

:-(

But, let me give you some other panels:
![image](https://user-images.githubusercontent.com/1108513/55578583-344b0080-570e-11e9-9698-94a652533ec4.png)


![image](https://user-images.githubusercontent.com/1108513/55578597-38771e00-570e-11e9-95ef-4fb657605576.png)


![image](https://user-images.githubusercontent.com/1108513/55578603-3d3bd200-570e-11e9-9ec5-ba467b7f6284.png)


![image](https://user-images.githubusercontent.com/1108513/55578609-42008600-570e-11e9-892a-abfcd814094f.png)
