### ISSUE TITLE
Need NMEA icon

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief-icons#72]
We need copies of this icon at 16px, 24px and 48px:
https://www.nmea.org/content/press_center/logos.asp

I _guess_ we would just use the dark-blue Debrief color.

**Comment by hlaposhka** [comment]
Do I need to replace the original color of the icon with dark-blue Debrief color?

**Comment by IanMayo** [comment]
Yes please Yana

**Comment by IanMayo** [comment]
Hey, I've no idea where that yellow bar came from :-)

![image](https://user-images.githubusercontent.com/1108513/59512578-eb06f200-8eb0-11e9-99d9-8ff14a5d7f98.png)

**Comment by IanMayo** [comment]
Fixed in #74
