### ISSUE TITLE
Icons for diary viewer

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief-icons#73]
We need some new icons for when we display a diary.

Here is a screen mockup:
![image](https://user-images.githubusercontent.com/1108513/59488545-c7738580-8e77-11e9-8caa-dd2186b29a1c.png)

The first 3 are: 
* change color `changeColor.png`
* edit .  `edit.png`
* delete . `delete.png`
![image](https://user-images.githubusercontent.com/1108513/59488972-ec1c2d00-8e78-11e9-9c0e-b8bd945457dc.png)

The last one is to show the current entry:
![image](https://user-images.githubusercontent.com/1108513/59488978-f1797780-8e78-11e9-8c46-39da272a4b3c.png)

We'd like them all at 16,24 and 48px please.

**Comment by hlaposhka** [comment]
Icon design should be like in the picture?

**Comment by IanMayo** [comment]
Yes - but you can make more attractive ones, if you like.

**Comment by hlaposhka** [comment]
I have already done icons but forgot to ask about the color of the icons. Will it be debrief-blue, blue & red or gray as a pictured?

**Comment by IanMayo** [comment]
I'm happy to leave it to your judgement.

Well, certainly Debrief colors.  But, the single-color blue looks ok to me.

**Comment by IanMayo** [comment]
Fixed in #75
