### ISSUE TITLE
Date format icon

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief-icons#76]
In our application we display the date-time that we're currently looking at:
![time panel](https://user-images.githubusercontent.com/1108513/66029449-36441f80-e4f7-11e9-82d5-860252e63992.png)

Depending on the size of the data being looked at, the user may wish to have the date formatted differently, so we provide a drop-down list of time formats:
![format drop-down](https://user-images.githubusercontent.com/1108513/66029494-4cea7680-e4f7-11e9-8a03-e15c4c93938e.png)

The cog icon isn't _great_ for this drop-down menu.  It would be better if it gave a hint that it's controlling the date-time format.

If I [Google](https://www.google.com/search?biw=1381&bih=1217&tbm=isch&sxsrf=ACYBGNRrLiaJ09cj-qtyNjcR-7kWstXLPw%3A1570005103745&sa=1&ei=b2CUXdmNLZ2KjLsPl-uw6A8&q=time+format+icon&oq=time+format+icon&gs_l=img.3..35i39.4768.5051..5614...0.0..0.59.224.4......0....1..gws-wiz-img.......0i7i30j0i7i5i30j0i8i7i30.LLpuDHqdCRk&ved=0ahUKEwiZgYTklP3kAhUdBWMBHZc1DP0Q4dUDCAc&uact=5) I get clock icons, with a config button.

But, I think you will struggle to fit the clock and the icon into 16px.  Aah, _maybe_ just a clock icon would do it.  Or, _maybe_ just a [date](date format icon) icon would do it.

Aah, I may be mistaken about what can be fitted into a 16px icon, since the existing one already contains a cog and a search icon.   Maybe it is possible to have a clock with a cog :-)

![image](https://user-images.githubusercontent.com/1108513/66036029-38f94180-e504-11e9-9df7-337a2b5103ee.png)

**Comment by hlaposhka** [comment]
@IanMayo  I made 4 options, I think the first most distinguishable in the size of 16pcs. I will attach in sizes of 16x16 and 48x48
![v1](https://user-images.githubusercontent.com/7010233/66331583-9560c480-e93b-11e9-9371-5a66322e7e7c.png)
![v2](https://user-images.githubusercontent.com/7010233/66331584-95f95b00-e93b-11e9-98e4-de07037e575b.png)
![v3](https://user-images.githubusercontent.com/7010233/66331585-95f95b00-e93b-11e9-8b3e-e2e73972e959.png)
![v4](https://user-images.githubusercontent.com/7010233/66331587-95f95b00-e93b-11e9-8f7e-fe31460c9655.png)
<img width="24" alt="v1" src="https://user-images.githubusercontent.com/7010233/66331605-9c87d280-e93b-11e9-9a28-dcf2cb598a04.png">
<img width="24" alt="v2" src="https://user-images.githubusercontent.com/7010233/66331606-9c87d280-e93b-11e9-9f45-0c2b2992e454.png">
<img width="24" alt="v3" src="https://user-images.githubusercontent.com/7010233/66331607-9c87d280-e93b-11e9-9459-09b780cd7a01.png">
<img width="24" alt="v4" src="https://user-images.githubusercontent.com/7010233/66331608-9d206900-e93b-11e9-95c7-f09556cbb5a1.png">

**Comment by IanMayo** [comment]
Nice work - you've done well with those 16px icons.

I did think the 4th one was best (with the calendar).  But, in that one, the clock element is really, really small.

So, I think the first one is my favourite.

(versions 2 and 3 are clever, when the combine the clock and the wheel, but I think the wheel (cog) component becomes less visible in those two).

Could you do a PR to introduce the first one at 16px, 24px, and 48px?  

It should be called `time_config.png`, please.

**Comment by hlaposhka** [comment]
@IanMayo  I worked a little with the calendar version, I slightly changed the initial objects for better readability. If this version is liked the most, maybe in this version we can use it
![v5-5](https://user-images.githubusercontent.com/7010233/66382891-ac97c480-e9c4-11e9-9792-0dfb67de64fe.png)
![v5](https://user-images.githubusercontent.com/7010233/66382892-ac97c480-e9c4-11e9-94c7-08ea3d572a9e.png)
![v6](https://user-images.githubusercontent.com/7010233/66382895-ac97c480-e9c4-11e9-85d6-c6839b737dd9.png)
![v7](https://user-images.githubusercontent.com/7010233/66382897-ac97c480-e9c4-11e9-8dd2-149b7227a505.png)
![v8](https://user-images.githubusercontent.com/7010233/66382898-ad305b00-e9c4-11e9-8df1-d4e5a2a149f7.png)
<img width="24" alt="v5-5" src="https://user-images.githubusercontent.com/7010233/66382963-cf29dd80-e9c4-11e9-82d3-2e88dbb7759a.png">
<img width="24" alt="v5" src="https://user-images.githubusercontent.com/7010233/66382965-cf29dd80-e9c4-11e9-9580-d150c080868f.png">
<img width="24" alt="v6" src="https://user-images.githubusercontent.com/7010233/66382966-cfc27400-e9c4-11e9-9069-158a1572f986.png">
<img width="24" alt="v7" src="https://user-images.githubusercontent.com/7010233/66382967-cfc27400-e9c4-11e9-8617-2f1a1aafba14.png">
<img width="24" alt="v8" src="https://user-images.githubusercontent.com/7010233/66382968-cfc27400-e9c4-11e9-87bc-cb928b38e762.png">

If not, then I will add version 4 to PR

**Comment by IanMayo** [comment]
The "24" is good, since it's the number format that we're editing.

What's the difference between icons 4 and 5?

**Comment by hlaposhka** [comment]
Sorry, in the last comment I meant the v4 file, this is the first option in the first comment that you selected.  The difference in the location of the digital format is "24".  I can also reduce the settings icon in these options

**Comment by IanMayo** [comment]
Ok. My favourite version is the number 5 in this set.  The `24` is easiest to read in this version.

Nice work.  So, copies of this at 16,24,48px, please.

**Comment by IanMayo** [comment]
Fixed in #77
