### ISSUE TITLE
Require icons with blue/red background

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief-icons#82]
For another web-based app I now realise I need copies of a set of icons with red & blue backgrounds.  These are different icons to the ones in the `svg` folder here.  I've attached a zip with the icons (you created them in Dec 2019).

[counters.zip](https://github.com/debrief/debrief-icons/files/6323575/counters.zip)

The shades of red & blue are the standard ones for this repo:
![image](https://user-images.githubusercontent.com/1108513/114990768-c3a85400-9e90-11eb-9a45-359b4a9e3c43.png)

The icons will look like this screenshot.  But, there will be a change.  The coloured border around it picture bit of the image will be smaller. So instead of looking like this:
![Screenshot 2021-04-16 at 09 36 37](https://user-images.githubusercontent.com/1108513/114996992-52b86a80-9e97-11eb-96e6-d55b89b97b25.png)

The picture bit will be relatively larger, like this:
![Screenshot 2021-04-16 at 09 26 26](https://user-images.githubusercontent.com/1108513/114997029-5ba93c00-9e97-11eb-92e0-aaae59934a94.png)

This is because the icons aren't going be viewed on a normal monitor - but on a screen mounted on the wall - so it's important that we make the picture part larger.

I'm pretty sure this a job for a text-editor more than a graphics program :-)

Actually - if you're going to find it a real chore, if you just make one icon then I can copy the change for the others.  But, if you are happy to do them all then that will help me :-)

The icons will go into a new folder for this repo, called `counters`

For the naming, the new versions of `frigate.svg` will be `red_frigate.svg` and `blue_frigate.svg`

**Comment by hlaposhka** [comment]
@IanMayo  I will do it, I think in series I will do it quickly. I will send you the first icon to visually check the size

**Comment by IanMayo** [comment]
Perfect, thanks :-)

**Comment by hlaposhka** [comment]
I created 2 icon with with different padding
I think v1 looks better
[example.zip](https://github.com/debrief/debrief-icons/files/6338139/example.zip)

**Comment by IanMayo** [comment]
Agreed. V1 looks better :-)

**Comment by IanMayo** [comment]
This is done.
